plugins {
    id 'com.android.application'
}

android {
    namespace 'rs.simovic.hyperdebloat'
    compileSdk 36

    defaultConfig {
        applicationId "rs.simovic.hyperdebloat"
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName "1.0"
    }

    buildFeatures {
        buildConfig true
        aidl true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation "dev.rikka.shizuku:api:13.1.5"
    implementation "dev.rikka.shizuku:provider:13.1.5"
}
